HW 1
dxvxlopxr/2024-2-VK-EDU-Frontend-A-Gavrilov pull request #1
Opened 2024-09-22 19:31 UTC by dxvxlopxr

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.

Что было сделано:
*
*
*

2024-09-24 06:35 UTC, nelkor requested changes
[+] Задания решены верно. Прекрасное решение первой задачи через логарифм. В остальных задачах проверки входящих аргументов на правильность.

[-] Абсолютно ужасный Code Style. И это не смотря на то, что я показывал, как легко автоматически отформатировать код. С другой стороны, скорее всего это специально, чтобы шпионы не смогли прочитать код.

[-] Export Default. Это плохой подход. Экспорты должны быть именованными.

Это опциональные недостатки, их можно поправить, а можно и не править. Возможно, в следующих заданиях исправление подобных недостатков станет обязательным. А вот отмеченные в коде комментарии надо поправить уже сейчас.

2024-09-24 06:35 UTC, nelkor commented on hw-1/package.json
> +    "mem-fs": "^4.0.0"
yo, mem-fs, generator-track-mail — этого не должно быть в devDependencies.

2024-09-24 06:35 UTC, nelkor commented on hw-1/correctSentence.test.js
> +test('returns correct sentence', () => {
Раз уж функция может выбросить исключение, надо проверить это поведение в тестах.

2024-09-24 14:54 UTC, nelkor approved these changes

2024-09-25 21:05 UTC, HaseProgram approved these changes
12!

2024-09-25 21:05 UTC, merged